use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# TcCacheWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :tc_cache, TcCacheWeb.Endpoint,
  load_from_system_env: true,
  url: [host: System.get_env("DOMAIN_NAME"), port: System.get_env("PORT")],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger,
  backends: [{ExSyslogger, :exsyslogger}]

config :logger, :exsyslogger,
  level: :info,
  ident: System.get_env("SYSLOG_PROGNAME"),
  facility: :local0

config :tc_cache, TcCache.Sync.Scheduler, enabled: true

config :tc_cache, TcCacheWeb.Endpoint,
  secret_key_base: "gCXlWQqLLNIieh/hI8ofkTXfUcGECSf7KDtJsdoOlApk4BCztMhSXv4OgIsyVya9"

# Configure your database
config :tc_cache, TcCache.Repo,
  adapter: Ecto.Adapters.MySQL,
  hostname: System.get_env("MYSQL_HOSTNAME"),
  username: System.get_env("MYSQL_USERNAME"),
  password: System.get_env("MYSQL_PASSWORD"),
  database: System.get_env("MYSQL_DB_NAME"),
  pool_size: 15
